
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: bd_sistema_facturacion   # debe coincidir con el que usas en la URL
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet

  springboot:
    image: bryanbf24/pos-api-spring
    container_name: spring_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "9898:8080"  # Spring Boot escucha en el 8080 dentro del contenedor
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_sistema_facturacion
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpass
    networks:
      - appnet

volumes:
  mysql_data:

networks:
  appnet:
